mysite/GUI/urls.py
from django.urls import path

from . import views

app_name = 'GUI'
urlpatterns = [
    path('', views.index, name='index'),
    path('FAQs/', views.FAQs, name='FAQs'),
    path('Manual/', views.Manual, name='Manual'),
    path('Results/', views.Results, name='Results'),
    path('Search/', views.Search, name='Search'),
    path('download/<str:filename>/', views.download_file, name='download_file'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('GUI/', include('GUI.urls')),
    path('admin/', admin.site.urls),
]

mysite/GUI/models.py
from django.db import models

# Create your models here.

mysite/GUI/forms.py
from django import forms


class SearchTwitter(forms.Form):
    name = forms.CharField(label="", max_length=25)

    # this file can be deleted if we are not using Django's premade forms

mysite/GUI/views.py
from django.shortcuts import render
import mimetypes
import os

# Create your views here.

from django.http import HttpResponse
from django.template import loader
from .forms import SearchTwitter # delete if not using forms.py
from .Web_Crawler import twitterCrawl
from .sentiment import AiSentiment

def index(request):
    return HttpResponse('hello world')

def FAQs(request):
    return render(request,'GUI/FAQsPage.html')

def Manual(request):
    return render(request,'GUI/ManualPage.html')

def Results(request):
    name = request.GET['name']
    SelfObject = twitterCrawl(v2=True)
    SelfObject.search_tweets_v2('"{}" lang:en'.format(name))
    AIObject = AiSentiment()
    AIObject.excactResults(SelfObject.results)
    AIObject.Curve()
    neutral = len(AIObject.data['Neutral'])
    negative = len(AIObject.data['Negative'])
    positive = len(AIObject.data['Positive'])
    totalTweets = neutral + negative + positive
    return render(request,'GUI/ResultsPage.html', {"PositiveSearchResults": positive, "NegativeSearchResults": negative, "NeutralSearchResults": neutral, "SearchTerm": name, "TotalTweets": totalTweets}) # name is placeholder until we implement AI

def Search(request):
    form = SearchTwitter() # have Django make a premade form for us?
    return render(request,'GUI/SearchPage.html', {"form": form}) # have Django make a premade form for us?

def download_file(request, filename=''):
    if filename != '':
        BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        filepath = BASE_DIR + '/GUI/Files/' + filename
        path = open(filepath, 'rb')
        mime_type, _ = mimetypes.guess_type(filepath)
        response = HttpResponse(path, content_type=mime_type)
        response['Content-Disposition'] = "attachment; filename=%s" % filename
        return response
    else:
        return render(request, 'GUI/ManualPage.html')

mysite/GUI/templates/GUI/FAQsPage.html
<!DOCTYPE html>
<html>
<head>
    <title>FAQsPage</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'GUI/style.css' %}">
</head>

<body>
    <a id="TweetCleanImage" href="{% url 'GUI:Search' %}">
        <img src="/static/GUI/images/TweetClean.png" alt="TweetClean" class="responsive">
    </a>
    <h1>FREQUENTLY ASKED QUESTIONS</h1>
    <div class="container">
        <div class="dropdown">
            <span>Q: How do I see frequently asked questions?</span>
            <div class="dropdown-content">
                <p><em>A: Click the FAQs link on the navbar.</em></p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="dropdown">
            <span>Q: How do I navigate this site?</span>
            <div class="dropdown-content">
                <p><em>A: Click the manuals link on the navbar.</em></p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="dropdown">
          <span>Q: What is this sites purpose?</span>
          <div class="dropdown-content">
              <p><em>A: This site provides users with the ability to analyse how popular 2 search terms are across Twitter.</em></p>
          </div>
        </div>
    </div>
    <div class="container">
        <div class="dropdown">
            <span>Q: How does this site work?</span>
            <div class="dropdown-content">
                <p><em>A: We use Twitter's API to search for tweets given the term you search for. Only tweets that are publicly available will be used. We go through the most recent 100 tweets with the given search term and show whether we believe they are positive, negative or neutral.</em></p>
            </div>
        </div>
    </div>
    <div class="navbar" id="myNavbar">
        <a href="{% url 'GUI:FAQs' %}">FAQs</a>
        <a href="{% url 'GUI:Manual' %}">Manual</a>
        <a href="{% url 'GUI:Search' %}">Search</a>
    </div>
</body>
</html>

mysite/GUI/templates/GUI/ManualPage.html
<!DOCTYPE html>
<html>
<head>
    <title>ManualsPage</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'GUI/style.css' %}">
</head>

<body>
    <a id="TweetCleanImage" href="{% url 'GUI:Search' %}">
        <img src="/static/GUI/images/TweetClean.png" alt="TweetClean" class="responsive">
    </a>
    <h1>Click the image below to download the user manual</h1>
    <div class="container">
        <a href="{% url 'GUI:download_file' filename='TweetCleanManual.pdf' %}">
        <img src="/static/GUI/images/manual_icon.png" alt="ManualTest">
        </a>
    </div>
    <div class="navbar" id="myNavbar">
        <a href="{% url 'GUI:FAQs' %}">FAQs</a>
        <a href="{% url 'GUI:Manual' %}">Manual</a>
        <a href="{% url 'GUI:Search' %}">Search</a>
    </div>
</body>
</html>

mysite/GUI/templates/GUI/ResultsPage.html
<!DOCTYPE html>
<html>
<head>
    <title>ResultsPage</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'GUI/style.css' %}">
</head>

<body>
    <a id="TweetCleanImage" href="{% url 'GUI:Search' %}">
        <img src="/static/GUI/images/TweetClean.png" alt="TweetClean" class="responsive">
    </a>
    <h1>RESULTS</h1>
    <p>We retrieved the last {{TotalTweets}} recent tweets containing your name...</p>
    <p>{{SearchTerm}}</p> <!-- this variable comes from the Search view and contains relevant data for display -->
    <div class="navbar" id="myNavbar">
        <a href="{% url 'GUI:FAQs' %}">FAQs</a>
        <a href="{% url 'GUI:Manual' %}">Manual</a>
        <a href="{% url 'GUI:Search' %}">Search</a>
    </div>

    <div id='piechart' align='center'></div>
    
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>

        <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <div class="container">
        <a id="graphImage" href="{% url 'GUI:Search' %}">
            <img src="/static/GUI/images/distChart.jpg" alt="distChart">
        </a>
    </div>

    <script type="text/javascript">
    // Load google charts
    google.charts.load('current', {'packages':['corechart']});
    google.charts.setOnLoadCallback(drawChart);
    function drawChart() {
      var data = google.visualization.arrayToDataTable([
      ['Sentiment', 'Number of Tweets'],
      ['Positive', {{PositiveSearchResults}}],
      ['Negative', {{NegativeSearchResults}}],
      ['Neutral', {{NeutralSearchResults}}],
    ]);
        var options = {'width':550, 'height':400, legend: {alignment: 'center', position: 'top'}, chartArea: {
      backgroundColor: {fill: '#00acee', fillOpacity: 0.1},}, backgroundColor: {fill: '#00acee',fillOpacity: 0.8}, colors: ['#32CD32', '#ff0000', '#A9A9A9']};
        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);
    }
    </script>
    <div class="container">
        <button class="button2" onclick="history.back()"><span>Go Back</span></button>
    </div>
</body>
</html> 

mysite/GUI/templates/GUI/SearchPage.html
<!DOCTYPE html>
<html>
<head>
    <title>SearchPage</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'GUI/style.css' %}">
</head>

<body>
    <a id="TweetCleanLogo" href="{% url 'GUI:Search' %}">
        <img src="/static/GUI/images/TweetClean.png" alt="TweetClean" class="responsive">
    </a>
    <div class="container">
        <form>
            <label for="name">Enter Your Twitter Name Here...</label><br>
            {{form.as_p}} <!-- this is here if we want Django to make the form for us -->
            <!--<input type="text" id="name" name="name" value="@"><br>-->
            <button id = "goButton" class="button" formaction="{% url 'GUI:Results' %}"><span>Go</span></button>
        </form>
    </div>
    <div class="navbar" id="myNavbar">
        <a href="{% url 'GUI:FAQs' %}">FAQs</a>
        <a href="{% url 'GUI:Manual' %}">Manual</a>
        <a href="{% url 'GUI:Search' %}">Search</a>
    </div>
    <script>
        var input = document.getElementById("name");
        input.addEventListener("keyup", function(event) {
            if (event.keyCode === 13) {
                event.preventDefault();
                document.getElementById("goButton").click();
            }
        });
    </script>
</body>
</html>